# .streamlit/secrets.toml

# Dán nguyên JSON Service Account (lấy từ Google Cloud > IAM > Service Accounts > Keys)
# Giữ nguyên dấu """ ... """
GOOGLE_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "YOUR_PROJECT_ID",
  "private_key_id": "YOUR_KEY_ID",
  "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
  "client_email": "YOUR_SERVICE_ACCOUNT@YOUR_PROJECT_ID.iam.gserviceaccount.com",
  "client_id": "YOUR_CLIENT_ID",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/YOUR_SERVICE_ACCOUNT%40YOUR_PROJECT_ID.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

# ID của Google Sheet dùng để ghi log (bảng quản lý)
# Ví dụ: 1jO2B5GawiRCSla0tqqC9rDdIu7lLtUuT-J-0cHerGH0
SHEET_ID = "1jO2B5GawiRCSla0tqqC9rDdIu7lLtUuT-J-0cHerGH0"

# ID của thư mục Google Drive để tải file lên
# Ví dụ: 0B85NRfuypJmeZWRYcXY3czdXcVk
FOLDER_ID = "0B85NRfuypJmeZWRYcXY3czdXcVk"
